ALTER TABLE profiles 
ADD COLUMN IF NOT EXISTS target_calories INTEGER DEFAULT 2000,
ADD COLUMN IF NOT EXISTS target_protein INTEGER DEFAULT 150,
ADD COLUMN IF NOT EXISTS target_carbs INTEGER DEFAULT 200,
ADD COLUMN IF NOT EXISTS target_fats INTEGER DEFAULT 65;
