import { StyleSheet } from 'react-native';

export const inventoryScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#020617',
  },
  hudHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingVertical: 15,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(34, 211, 238, 0.3)',
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
  },
  hudLeft: {
    flexDirection: 'column',
    justifyContent: 'center',
    gap: 2,
  },
  hudName: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 16,
    fontFamily: 'Exo2-Regular',
  },
  hudStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  hudStatText: {
    fontSize: 10,
    fontWeight: 'bold',
    color: '#94a3b8',
    fontFamily: 'Exo2-Regular',
  },
  hudLevelValue: {
    color: '#22d3ee',
  },
  hudCPValue: {
    color: '#fbbf24',
  },
  hudRight: {
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 12,
    borderRadius: 9999,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.1)',
    height: 28,
    flexDirection: 'row',
    gap: 6,
  },
  hudCenter: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  hudLabel: {
    color: 'rgba(34, 211, 238, 0.8)',
    fontSize: 9,
    fontWeight: '900',
    letterSpacing: 1.5,
    fontFamily: 'Exo2-Regular',
  },
  hudValue: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '900',
    fontFamily: 'Exo2-Regular',
    textTransform: 'uppercase',
    fontStyle: 'italic',
  },
  rankValue: {
    fontSize: 14,
    fontWeight: '900',
  },
  statValueContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 2,
  },
  statValuePrefix: {
    fontSize: 12,
    fontWeight: '900',
    color: '#22d3ee',
    fontStyle: 'italic',
  },
  headerCurrencyContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  statsBtn: {
    borderWidth: 1,
    borderColor: 'rgba(6, 182, 212, 0.5)',
    height: 28,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(6, 182, 212, 0.1)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 4,
  },
  statsIcon: {
    width: 14,
    height: 14,
  },
  currencyPillPurple: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(88, 28, 135, 0.3)',
    borderWidth: 1,
    borderColor: 'rgba(168, 85, 247, 0.4)',
    borderRadius: 9999,
    paddingHorizontal: 10,
    height: 28,
    gap: 4,
  },
  currencyTextPurple: {
    color: '#e9d5ff',
    fontSize: 11,
    fontWeight: '900',
  },
  currencyPillYellow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(113, 63, 18, 0.3)',
    borderWidth: 1,
    borderColor: 'rgba(234, 179, 8, 0.4)',
    borderRadius: 9999,
    paddingHorizontal: 10,
    height: 28,
    gap: 4,
  },
  currencyTextYellow: {
    color: '#fef08a',
    fontSize: 11,
    fontWeight: '900',
  },
  currencyIcon: {
    width: 12,
    height: 12,
  },
  scrollViewContent: {
    flexGrow: 1,
  },
  loadingText: {
    color: '#22d3ee',
    textAlign: 'center',
    marginTop: 50,
    fontSize: 12,
    fontWeight: 'bold',
    letterSpacing: 2,
  },
});
