import { Dimensions, StyleSheet } from 'react-native';

/**
 * System window styling — aligned with StatusWindowModal, ChestOpeningModal, SoloLevelingPanelFrame:
 * HUD frame rgba(4,12,28), cyan border rgba(0,210,255), accent #00d2ff, Exo2 / Montserrat headers.
 */
const { width } = Dimensions.get('window');

const HUD_BG = 'rgba(4, 12, 28, 0.95)';
const HUD_BORDER = 'rgba(0, 210, 255, 0.3)';
const PANEL_BG = 'rgba(0, 34, 68, 0.3)';
const PANEL_BORDER = 'rgba(0, 210, 255, 0.2)';
const BACKDROP = 'rgba(2, 4, 10, 0.85)';
const CYAN = '#00d2ff';
const TEXT_MUTED = 'rgba(0, 210, 255, 0.55)';
const GLOW_SHADOW = '#0066ff';

export const inventoryModalsStyles = StyleSheet.create({
  section: {
    marginHorizontal: 16,
    marginBottom: 30,
  },
  sectionHeader: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 3,
    marginBottom: 16,
    paddingVertical: 10,
    backgroundColor: 'rgba(0, 34, 68, 0.4)',
    borderLeftWidth: 3,
    borderLeftColor: CYAN,
    paddingHorizontal: 15,
    fontFamily: 'Exo2-Bold',
    color: CYAN,
    textShadowColor: 'rgba(0, 210, 255, 0.45)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  equippedGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: 8,
  },
  /** Accessories row: aura, eyes, head, face, shoulder, multi — single row, equal columns */
  equippedAccessoryRow: {
    flexDirection: 'row',
    flexWrap: 'nowrap',
    alignItems: 'stretch',
    gap: 4,
    width: '100%',
  },
  equippedAccessorySlot: {
    flex: 1,
    minWidth: 0,
    aspectRatio: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 3,
    borderRadius: 2,
    borderWidth: 1,
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: PANEL_BG,
    borderColor: PANEL_BORDER,
  },
  equippedAccessoryMultiSlot: {
    flex: 1,
    minWidth: 0,
    aspectRatio: 1,
    flexDirection: 'column',
    justifyContent: 'center',
    padding: 2,
    backgroundColor: PANEL_BG,
    borderColor: HUD_BORDER,
    borderWidth: 1,
    borderRadius: 2,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: GLOW_SHADOW,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 4,
  },
  equippedAccessoryMultiGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 2,
    width: '100%',
    justifyContent: 'center',
    alignContent: 'center',
  },
  equippedAccessoryMiniSlot: {
    width: '31%',
    aspectRatio: 1,
    backgroundColor: 'rgba(2, 8, 20, 0.5)',
    borderColor: 'rgba(0, 210, 255, 0.18)',
    borderWidth: 1,
    borderRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  equippedAccessoryItemMediaContainer: {
    position: 'relative',
    zIndex: 10,
    width: '72%',
    maxWidth: 34,
    maxHeight: 34,
    aspectRatio: 1,
    alignSelf: 'center',
  },
  equippedAccessoryItemMedia: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  equippedAccessorySlotLabel: {
    position: 'absolute',
    bottom: 1,
    left: 0,
    right: 0,
    paddingHorizontal: 1,
    fontSize: 5,
    fontWeight: '800',
    textTransform: 'uppercase',
    color: 'rgba(0, 210, 255, 0.5)',
    letterSpacing: 0.2,
    fontFamily: 'Exo2-Regular',
    textAlign: 'center',
  },
  equippedSlot: {
    flex: 1,
    aspectRatio: 1,
    minWidth: width < 640 ? '18%' : '19%',
    maxWidth: width < 640 ? '19%' : '19%',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: 8,
    borderRadius: 2,
    borderWidth: 1,
    position: 'relative',
    overflow: 'hidden',
    backgroundColor: PANEL_BG,
    borderColor: PANEL_BORDER,
  },
  emptySlot: {
    backgroundColor: 'rgba(0, 0, 0, 0.35)',
    borderColor: 'rgba(0, 210, 255, 0.15)',
    borderStyle: 'dashed',
  },
  equipmentSlotSelected: {
    borderWidth: 2,
    borderColor: CYAN,
    shadowColor: CYAN,
    shadowOpacity: 0.45,
    shadowRadius: 10,
  },
  equipmentPickerHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    paddingVertical: 6,
  },
  equipmentPickerTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: '#e6ffff',
    textTransform: 'uppercase',
    letterSpacing: 2,
    fontFamily: 'Exo2-Bold',
    textShadowColor: 'rgba(0, 210, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  equipmentPickerClear: {
    fontSize: 10,
    fontWeight: '800',
    color: CYAN,
    fontFamily: 'Exo2-Regular',
    letterSpacing: 1,
  },
  equipmentPickerEmpty: {
    fontSize: 11,
    color: TEXT_MUTED,
    paddingVertical: 12,
    fontFamily: 'Exo2-Regular',
    letterSpacing: 1,
  },
  equipmentPickerList: {
    gap: 8,
  },
  equipmentPickerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: PANEL_BG,
    borderRadius: 2,
    borderWidth: 1,
    borderColor: PANEL_BORDER,
    paddingVertical: 8,
    paddingHorizontal: 10,
  },
  equipmentPickerRowMediaWrap: {
    position: 'relative',
    width: 44,
    height: 44,
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: 'rgba(2, 8, 20, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.2)',
  },
  equipmentPickerGlow: {
    ...StyleSheet.absoluteFillObject,
    opacity: 0.45,
  },
  equipmentPickerRowMedia: {
    width: 40,
    height: 40,
    resizeMode: 'contain',
  },
  equipmentPickerRowInfo: {
    flex: 1,
    minWidth: 0,
  },
  equipmentPickerRowName: {
    color: '#e6ffff',
    fontSize: 12,
    fontWeight: '800',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 0.5,
  },
  equipmentPickerRowRarity: {
    fontSize: 9,
    fontWeight: '700',
    marginTop: 2,
    fontFamily: 'Exo2-Regular',
    textTransform: 'uppercase',
  },
  equipmentPickerEquipBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 2,
    borderWidth: 1,
  },
  equipmentPickerEquipBtnActive: {
    borderColor: 'rgba(0, 210, 255, 0.5)',
    backgroundColor: 'rgba(0, 55, 90, 0.45)',
  },
  equipmentPickerUnequipBtn: {
    borderColor: 'rgba(239, 68, 68, 0.45)',
    backgroundColor: 'rgba(80, 20, 20, 0.35)',
  },
  equipmentPickerEquipBtnText: {
    fontSize: 9,
    fontWeight: '900',
    color: '#e6ffff',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 1,
  },
  equippedItemContent: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radiatingEnergy: {
    position: 'absolute',
    width: '130%',
    height: '130%',
    borderRadius: 9999,
    opacity: 0.12,
  },
  equippedItemMediaContainer: {
    position: 'relative',
    zIndex: 10,
    width: 40,
    height: 40,
  },
  equippedItemMedia: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  slotLabel: {
    position: 'absolute',
    bottom: 4,
    fontSize: 6,
    fontWeight: '800',
    textTransform: 'uppercase',
    color: 'rgba(0, 210, 255, 0.45)',
    letterSpacing: 1,
    fontFamily: 'Exo2-Regular',
  },
  multiAccessorySlot: {
    flex: 1,
    aspectRatio: 1,
    minWidth: width < 640 ? '18%' : '19%',
    maxWidth: width < 640 ? '19%' : '19%',
    flexDirection: 'column',
    padding: 8,
    backgroundColor: PANEL_BG,
    borderColor: HUD_BORDER,
    borderWidth: 1,
    borderRadius: 2,
    position: 'relative',
    overflow: 'hidden',
    shadowColor: GLOW_SHADOW,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 4,
  },
  multiAccessoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 4,
    width: '100%',
    height: 'auto',
    marginBottom: 8,
  },
  miniAccessorySlot: {
    width: '31%',
    aspectRatio: 1,
    backgroundColor: 'rgba(2, 8, 20, 0.5)',
    borderColor: 'rgba(0, 210, 255, 0.18)',
    borderWidth: 1,
    borderRadius: 2,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    overflow: 'hidden',
  },
  radiatingEnergyMicro: {
    position: 'absolute',
    width: '116%',
    height: '116%',
    borderRadius: 9999,
    opacity: 0.35,
  },
  miniAccessoryMediaContainer: {
    position: 'relative',
    zIndex: 10,
    width: '100%',
    height: '100%',
    padding: 2,
  },
  miniAccessoryMedia: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: BACKDROP,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 16,
  },
  itemDetailModalContent: {
    backgroundColor: HUD_BG,
    borderColor: HUD_BORDER,
    borderWidth: 1,
    borderRadius: 2,
    padding: 20,
    maxWidth: width * 0.9,
    width: '100%',
    position: 'relative',
    shadowColor: GLOW_SHADOW,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 30,
    elevation: 12,
    alignItems: 'center',
  },
  closeModalButton: {
    position: 'absolute',
    top: 8,
    right: 8,
    zIndex: 1,
    width: 28,
    height: 28,
    padding: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.35)',
    backgroundColor: 'rgba(2, 12, 32, 0.85)',
  },
  itemDetailImageWrapper: {
    width: 64,
    height: 64,
    borderRadius: 2,
    backgroundColor: 'rgba(2, 8, 20, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.35)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    marginBottom: 12,
  },
  itemDetailImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  itemDetailName: {
    fontSize: 17,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 2,
    fontFamily: 'Exo2-Bold',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 210, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  itemDetailSlot: {
    fontSize: 11,
    color: CYAN,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 10,
    letterSpacing: 3,
    fontFamily: 'Exo2-Regular',
    textShadowColor: 'rgba(0, 210, 255, 0.45)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  itemRequirementsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  requirementBadgeYellow: {
    backgroundColor: 'rgba(0, 55, 80, 0.5)',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.35)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  requirementBadgeBlue: {
    backgroundColor: 'rgba(0, 55, 80, 0.5)',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.35)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  requirementBadgePink: {
    backgroundColor: 'rgba(0, 55, 80, 0.5)',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.35)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  requirementBadgeText: {
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    color: '#e6ffff',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 1,
  },
  itemDetailDescription: {
    fontSize: 13,
    color: 'rgba(230, 255, 255, 0.88)',
    marginBottom: 12,
    lineHeight: 20,
    textAlign: 'center',
    fontFamily: 'Exo2-Regular',
  },
  itemDetailBonuses: {
    fontSize: 11,
    color: CYAN,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 0.5,
  },
  itemDetailAnimated: {
    fontSize: 11,
    color: '#00e5ff',
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 2,
  },
  itemDetailRarity: {
    fontSize: 11,
    color: '#e6ffff',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 12,
    textAlign: 'center',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 2,
  },
  itemDetailEquippedStatus: {
    fontSize: 11,
    fontWeight: 'bold',
    marginBottom: 12,
    textAlign: 'center',
    fontFamily: 'Exo2-Regular',
  },
  closeButtonPrimary: {
    width: '100%',
    paddingVertical: 12,
    backgroundColor: 'rgba(0, 34, 68, 0.45)',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.4)',
    marginTop: 8,
    overflow: 'hidden',
  },
  closeButtonPrimaryText: {
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    textAlign: 'center',
    color: '#e6ffff',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 2,
  },
  customizationModalContent: {
    backgroundColor: HUD_BG,
    borderColor: HUD_BORDER,
    borderWidth: 1,
    borderRadius: 2,
    paddingTop: 16,
    paddingBottom: 18,
    paddingHorizontal: 14,
    maxWidth: width * 0.92,
    width: '100%',
    maxHeight: '90%',
    position: 'relative',
    shadowColor: GLOW_SHADOW,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 30,
    elevation: 12,
    alignItems: 'stretch',
  },
  closeModalButtonAbsolute: {
    position: 'absolute',
    top: 6,
    right: 6,
    zIndex: 210,
    width: 28,
    height: 28,
    padding: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(2, 12, 32, 0.92)',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.35)',
  },
  customizationModalHeaderContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginBottom: 4,
    width: '100%',
    paddingHorizontal: 8,
  },
  customizationModalHeader: {
    fontSize: 16,
    fontWeight: '600',
    textTransform: 'uppercase',
    letterSpacing: 2,
    color: '#e6ffff',
    fontFamily: 'Montserrat-Bold',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 210, 255, 0.8)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 15,
  },
  customizationModalIcon: {
    width: 42,
    height: 42,
    flexShrink: 0,
  },
  customizationModalSubHeader: {
    fontSize: 10,
    color: TEXT_MUTED,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    letterSpacing: 3,
    marginBottom: 20,
    fontFamily: 'Exo2-Regular',
  },
  emptyCustomizationPanel: {
    backgroundColor: 'rgba(0, 34, 68, 0.25)',
    borderColor: 'rgba(0, 210, 255, 0.25)',
    borderWidth: 1,
    borderStyle: 'dashed',
    padding: 36,
    alignItems: 'center',
    borderRadius: 2,
    width: '100%',
  },
  emptyCustomizationEmoji: {
    fontSize: 36,
    marginBottom: 12,
    opacity: 0.55,
  },
  emptyCustomizationText: {
    fontSize: 12,
    color: 'rgba(230, 255, 255, 0.75)',
    fontWeight: 'bold',
    textTransform: 'uppercase',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 1,
    textAlign: 'center',
  },
  emptyCustomizationSubText: {
    fontSize: 9,
    color: TEXT_MUTED,
    marginTop: 6,
    textTransform: 'uppercase',
    fontFamily: 'Exo2-Regular',
    letterSpacing: 2,
    textAlign: 'center',
  },
  customizationGridContainer: {
    flexGrow: 1,
    paddingBottom: 20,
  },
  customizationGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 12,
    paddingHorizontal: 6,
  },
  customizationItemCard: {
    width: width < 640 ? '46%' : '30%',
    paddingVertical: 14,
    paddingHorizontal: 10,
    flexDirection: 'column',
    alignItems: 'center',
    textAlign: 'center',
    borderRadius: 2,
    borderWidth: 1,
    borderColor: PANEL_BORDER,
    backgroundColor: PANEL_BG,
    position: 'relative',
  },
  customizationItemCardEquipped: {
    backgroundColor: 'rgba(0, 45, 75, 0.45)',
    shadowColor: GLOW_SHADOW,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 16,
    borderColor: 'rgba(0, 210, 255, 0.5)',
    borderWidth: 1.5,
  },
  customizationItemImageWrapper: {
    position: 'relative',
    width: 80,
    height: 80,
    marginBottom: 10,
    borderRadius: 9999,
    alignItems: 'center',
    justifyContent: 'center',
  },
  customizationItemPulse: {
    position: 'absolute',
    inset: 0,
    borderRadius: 9999,
    opacity: 0.18,
  },
  customizationItemImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
    borderRadius: 9999,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 210, 255, 0.45)',
    position: 'relative',
    zIndex: 10,
  },
  customizationItemName: {
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
    color: '#e6ffff',
    letterSpacing: 1,
    marginBottom: 4,
    fontFamily: 'Exo2-Bold',
    textAlign: 'center',
  },
  customizationItemRarity: {
    fontSize: 8,
    color: TEXT_MUTED,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    marginBottom: 10,
    lineHeight: 12,
    fontFamily: 'Exo2-Regular',
    letterSpacing: 1,
  },
  customizationEquipButton: {
    width: '100%',
    paddingVertical: 8,
    borderRadius: 2,
  },
  customizationUnequipButton: {
    backgroundColor: 'rgba(80, 25, 25, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(239, 68, 68, 0.4)',
  },
  customizationEquipButtonActive: {
    backgroundColor: 'rgba(0, 80, 95, 0.55)',
    borderWidth: 1,
    borderColor: 'rgba(0, 210, 255, 0.45)',
    shadowColor: CYAN,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.35,
    shadowRadius: 10,
    elevation: 4,
  },
  customizationEquipButtonText: {
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
    textAlign: 'center',
    color: '#e6ffff',
    fontFamily: 'Exo2-Bold',
    letterSpacing: 1.5,
  },
});
