import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const inventoryAvatarStyles = StyleSheet.create({
  avatarSection: {
    flexDirection: 'column',
    alignItems: 'center',
    paddingVertical: 30,
  },
  avatarContainer: {
    position: 'relative',
    width: width < 640 ? width * 0.7 : 224,
    height: width < 640 ? width * 0.7 : 224,
    shadowColor: '#3b82f6',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 25,
    alignSelf: 'center',
  },
  absoluteView: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  avatarButtonsContainerLeft: {
    position: 'absolute',
    top: 0,
    left: -53,
    flexDirection: 'column',
    gap: 12,
  },
  avatarButtonsContainerRight: {
    position: 'absolute',
    top: 0,
    right: -53,
    flexDirection: 'column',
    gap: 12,
  },
  avatarButton: {
    padding: 10,
    backgroundColor: 'rgba(6, 182, 212, 0.2)',
    borderColor: '#06b6d4',
    borderWidth: 1,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backgroundButton: {
    padding: 10,
    backgroundColor: 'rgba(6, 182, 212, 0.2)',
    borderColor: '#06b6d4',
    borderWidth: 1,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  swapButton: {
    padding: 10,
    backgroundColor: 'rgba(6, 182, 212, 0.2)',
    borderColor: '#06b6d4',
    borderWidth: 1,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  swapButtonActive: {
    backgroundColor: 'rgba(6, 182, 212, 0.3)',
    borderColor: '#06b6d4',
  },
  swapButtonIcon: {
    fontSize: 18,
  },
  petAvatarContainer: {
    width: '100%',
    height: '100%',
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(6, 182, 212, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  petAvatarImage: {
    width: '80%',
    height: '80%',
  },
  noPetPlaceholder: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  noPetText: {
    color: 'rgba(6, 182, 212, 0.5)',
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 2,
  },
  avatarButtonIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  statsContainer: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 24,
    backgroundColor: 'rgba(15, 23, 42, 0.9)',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(34, 211, 238, 0.2)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statItem: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  statValuePrefix: {
    fontSize: 12,
    fontWeight: '900',
    color: '#22d3ee',
    fontStyle: 'italic',
  },
  statLabel: {
    fontSize: 9,
    color: 'rgba(34, 211, 238, 0.7)',
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1,
    marginBottom: 0,
  },
  statValue: {
    fontSize: 16,
    fontWeight: '900',
    color: '#fff',
    fontFamily: 'Exo2-Regular',
    textShadowColor: 'rgba(34, 211, 238, 0.3)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 5,
  },
  statDivider: {
    width: 1,
    height: 30,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    alignSelf: 'center',
  },
  renameInput: {
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    borderColor: '#06b6d4',
    borderWidth: 1,
    borderRadius: 4,
    paddingVertical: 4,
    paddingHorizontal: 8,
    color: '#fff',
    fontSize: 16,
  },
});
