import { Dimensions, StyleSheet } from 'react-native';

const { width } = Dimensions.get('window');

export const inventoryGridStyles = StyleSheet.create({
  section: {
    marginHorizontal: 16,
    marginBottom: 30,
  },
  sectionHeader: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 3,
    marginBottom: 16,
    paddingVertical: 10,
    backgroundColor: 'rgba(34, 211, 238, 0.1)',
    borderLeftWidth: 4,
    borderLeftColor: '#22d3ee',
    paddingHorizontal: 15,
    fontFamily: 'Exo2-Regular',
  },
  inventoryHeader: {
    marginBottom: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    backgroundColor: 'rgba(15, 23, 42, 0.7)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    paddingHorizontal: 12,
    borderRadius: 4,
  },
  inventoryHeaderText: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    letterSpacing: 1.5,
    fontFamily: 'Exo2-Regular',
  },
  inventoryIcon: {
    width: 20,
    height: 20,
    resizeMode: 'contain',
  },
  filterBar: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    height: 48,
  },
  filterTabsContainer: {
    paddingHorizontal: 12,
    alignItems: 'center',
    gap: 20,
    flexGrow: 1,
  },
  filterTab: {
    paddingVertical: 12,
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterTabActive: {},
  filterTabText: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    color: 'rgba(255, 255, 255, 0.5)',
    letterSpacing: 1,
    fontFamily: 'Exo2-Regular',
  },
  filterTabTextActive: {
    color: '#fbbf24',
    textShadowColor: 'rgba(251, 191, 36, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
  },
  activeTabIndicator: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    backgroundColor: '#fbbf24',
    borderRadius: 2,
    shadowColor: '#fbbf24',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 4,
  },
  sortButton: {
    paddingHorizontal: 12,
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(255, 255, 255, 0.1)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
  },
  sortButtonActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
  },
  sortButtonText: {
    fontSize: 9,
    fontWeight: '900',
    textTransform: 'uppercase',
    color: '#60a5fa',
    letterSpacing: 1,
  },
  inventoryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'flex-start',
    gap: 12,
  },
  noItemsText: {
    fontSize: 10,
    color: '#6b7280',
    fontStyle: 'italic',
    flex: 1,
    textAlign: 'center',
    marginTop: 20,
  },
  inventoryItemCard: {
    width: width < 640 ? '31%' : '23%',
    aspectRatio: 0.75,
    padding: 10,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(51, 65, 85, 0.5)',
    backgroundColor: '#0f172a',
    overflow: 'hidden',
    position: 'relative',
  },
  inventoryItemCardEquipped: {
    borderColor: 'rgba(34, 197, 94, 0.4)',
    backgroundColor: 'rgba(15, 23, 42, 1)',
    borderWidth: 1.5,
  },
  inventoryItemMediaWrapper: {
    position: 'relative',
    width: 48,
    height: 48,
    marginBottom: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  radiatingEnergyLarge: {
    position: 'absolute',
    width: '150%',
    height: '150%',
    borderRadius: 9999,
    opacity: 0.2,
  },
  inventoryItemMediaContainer: {
    position: 'relative',
    zIndex: 10,
    width: '100%',
    height: '100%',
    padding: 4,
  },
  inventoryItemMedia: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  inventoryItemName: {
    fontSize: 10,
    fontWeight: '900',
    textTransform: 'uppercase',
    textAlign: 'center',
    lineHeight: 13,
    color: '#f8fafc',
    marginBottom: 10,
    letterSpacing: 0.5,
  },
  equipUnequipButton: {
    width: '100%',
    paddingVertical: 4,
    borderRadius: 2,
    marginTop: 'auto',
  },
  equipButton: {
    backgroundColor: 'rgba(22, 101, 52, 0.4)',
    borderWidth: 1,
    borderColor: '#16a34a',
  },
  unequipButton: {
    backgroundColor: 'rgba(127, 29, 29, 0.4)',
    borderWidth: 1.5,
    borderColor: '#991b1b',
  },
  equipUnequipButtonText: {
    fontSize: 7,
    fontWeight: '900',
    textTransform: 'uppercase',
    textAlign: 'center',
    color: '#fff',
    letterSpacing: 1,
  },
  quantityBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: 'rgba(0,0,0,0.6)',
    paddingHorizontal: 4,
    borderRadius: 4,
    zIndex: 20,
  },
  quantityText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
});
